In [3]:
import numpy as np
import time

In [4]:
x = np.random.random(10000000)

In [5]:
x

array([0.22510084, 0.17855663, 0.84232857, ..., 0.8424843 , 0.98449744,
       0.35817757])

In [6]:
len(x)

10000000

## Time the numpy calculations

## VS normal python calculations

In [7]:
start = time.time()
ans = np.mean(x)
print(ans, time.time()-start)

0.5000703846659768 0.00555872917175293


In [8]:
start = time.time()
ans = sum(x)/len(x)
print(ans, time.time()-start)

0.5000703846660486 0.3620929718017578


### Creating and saving nd arrays

In [10]:
x = np.array([1.0,2,44.5], dtype= np.int64)

In [11]:
print(x)

[ 1  2 44]


In [12]:
x

array([ 1,  2, 44])

In [13]:
# Saving the array
np.save('sample_np_array', x)

In [14]:
# Loading the array
y = np.load('sample_np_array.npy')

In [15]:
print(y)

[ 1  2 44]
